version: '3'
services:
  marklogic.latest:
    image: "mlregistry.marklogic.com/marklogic/latest"
    ports:
    # choose what ports you want to expose (at least 8000 8001 8002)
      - "8000-8050:8000-8050"
    hostname: "marklogic.latest"
    container_name: "marklogic.latest"
    volumes:
       - ./logs/marklogic.latest:/var/opt/MarkLogic/Logs
       - ./Data:/data

# optionally specify the subnet
#networks:
#  default:
#    driver: bridge
#    ipam:
#      config:
#       - subnet: 172.68.0.0/16
